spring:
  application:
    name: jokemachine
  datasource:
    password: ${db_password}
    username: ${db_user}
    url: ${db_url}
    driver-class-name: ${db_driver}

telegram:
  bot:
    name: ${bot_name}
    token: ${bot_token}

openrouter:
  api:
    key: ${api_key}
    url: ${api_url}
